sudo: required
services: docker
language: ruby
branches:
    only:
        - master
before_install:
    - docker pull johntfoster/texlive
script: 
    - docker run --rm -it -v $(pwd):/var/texlive  johntfoster/texlive latexmk -latex='latex -shell-esc -interaction=nonstopmode %O \\\def\\\isinstitutional{1} \\\input %S'
    - docker run --rm -it -v $(pwd):/var/texlive  johntfoster/texlive latexmk -C
    - docker run --rm -it -v $(pwd):/var/texlive  johntfoster/texlive latexmk cv.tex
    - docker run --rm -it -v $(pwd):/var/texlive  johntfoster/texlive latexmk -pdf cv.tex
    - docker run --rm -it -v $(pwd):/var/texlive  johntfoster/texlive vi cv.html +"set fileencoding=utf-8" +qall +wq
    - docker run --rm -it -v $(pwd):/var/texlive  johntfoster/texlive pandoc cv.html -o cv.docx
after_success:
    - git config --global user.email ${GIT_EMAIL}
    - git config --global user.name ${GIT_NAME}
    - git clone --quiet --branch=travis-build https://${GH_TOKEN}@github.com/jontateixeira/my_CV travis-build > /dev/null
    - cd travis-build
    - cp -f $HOME/workspace/Projects/my_CV/cv.pdf .
    - cp -f $HOME/workspace/Projects/my_CV/cv.html .
    - cp -f $HOME/workspace/Projects/my_CV/cv.docx .
    - git add cv.pdf cv.html cv.docx
    - git commit -m "Travis CI autocommit from travis build ${TRAVIS_BUILD_NUMBER}"
    - git push -fq origin travis-build > /dev/null
    - gem install travis
    - travis restart -r jontateixeira/jontateixeira.github.io --token ${TRAVIS_TOKEN} --skip-completion-check


